version: '3.8'

services:
  app:
    container_name: debian-manager
    image: debian-manager:latest
    build: .
    user: "0:0"
    ports:
      - "8300:8300"
    privileged: true
    volumes:
      # Mount the entire host filesystem to /host
      - /:/host
      # We still need the host's run directory for socket communication
      - /run:/run
    restart: unless-stopped
