version: '3.8'

services:
  package-manager:
    build: .
    user: "0:0"
    ports:
      - "8300:8300"
    privileged: true
    volumes:
      - /var/lib/dpkg:/var/lib/dpkg
      - /etc/apt/sources.list:/etc/apt/sources.list:ro
      - /etc/apt/sources.list.d:/etc/apt/sources.list.d:ro
      - /etc/apt/keyrings:/etc/apt/keyrings:ro
      - /etc/apt/mirrors:/etc/apt/mirrors:ro
      - /usr/share/keyrings:/usr/share/keyrings:ro
      - /var/cache/apt:/var/cache/apt
      - /var/lib/apt:/var/lib/apt
    restart: unless-stopped
